### ISSUE TITLE
New participant registration page

### ISSUE THREAD

**Issue by RobGruhl** [Nordstrom/hello-retail#19]
The first page every user should come to is the new participant registration page, asking them to log in via amazon and select from Merchant, Photographer, or Customer.  If they select photographer, a well-formed phone number is required.  This page generates New Customer, New Photographer, or New Merchant events.  The events have the participant's name and in the case of photographer, phone number.

**Comment by erikerikson** [comment]
Not sure that is exactly how we'd like the registration to behave.  I think we want to allow users to play multiple roles, even though, in practice, we expect them to only use one of them.  If only for testing/demoing purposes.

**Comment by RobGruhl** [comment]
We used amazon login and only photographers need extra information.
