### ISSUE TITLE
Hard-Coded References to 'demo' Stage

### ISSUE THREAD

**Issue by erikerikson** [Nordstrom/hello-retail#25]
Here:
https://github.com/Nordstrom/hello-retail/blob/initial-formation/web/components/app.jsx

Lines 19, 34, 71, 72, 86, 87

**Comment by erikerikson** [comment]
Sorry I missed this in review.

**Comment by erikerikson** [comment]
I'll just deal with this in exports consolidation PR we discussed

**Comment by gwsii** [comment]
Not a problem. https://webpack.js.org/plugins/define-plugin/ can be used to read and inject the appropriate stage name when building.

**Comment by erikerikson** [comment]
oh, yeah...  mind handling it once the PR is merged?  Spaced on the context difference...

**Comment by gwsii** [comment]
We now have a solution via the NPM script command "web:build" which uses a Serverless plugin and values in the serverless.yml script to determine the necessary settings per environment. This written to the config.js which is then included in the bundle.js.
